# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(error_messages={'unique': 'A blog with that blog already exists.'}, max_length=20, unique=True)),
                ('blog_content', models.CharField(max_length=150)),
                ('blog_user', models.CharField(max_length=150)),
                ('date_creared', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
        ),
    ]
