# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180306_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(error_messages={'unique': 'A blog with that blog name already exists.'}, max_length=20, unique=True),
        ),
    ]
